config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :items do
    resources :comments
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    #http_basic_authenticate_with name: "dhh", password: "secret",
     #   only: :destroy

    def create
        @item = Item.find(params[:item_id])
        @comment = @item.comments.create(comment_params)
        redirect_to item_path(@item)
    end

    def destroy
        @item = Item.find(params[:item_id])
        @comment = @item.comments.find(params[:id])
        @comment.destroy

        redirect_to item_path(@item)
    end

    private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    #http_basic_authenticate_with name: "dhh", password: "secret",
     #   except: [:index, :show]

    def index
        @items = Item.all
    end

    def show
        @item = Item.find(params[:id])
    end

    def new
        @item = Item.new
    end

    def edit
        @item = Item.find(params[:id])
    end

    def create
        #render plain: params[:item].inspect
        puts "Hola"
        puts params[:item]

        @item = Item.new(item_params)

        if @item.save
            redirect_to @item
        else
            render 'new'
        end
    end

    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)
            redirect_to @item
        else
            render 'edit'
        end
    end

    def destroy
        @item = Item.find(params[:id])
        @item.destroy

        redirect_to items_path
    end

    private
    def item_params
        params.require(:item).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.item, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @item, @item.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1 class="custom-class">Hello World!</h1>
<%= link_to 'My Blog', controller: 'items' %>

app/views/items/_form.html.erb
<%= form_with(model: @item, local: true) do |form| %>

  <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@item.errors.count, "error") %> prohibited
          this item from being saved:
        </h2>
        <ul>
          <% @item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form'  %>

<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<%= link_to 'Home', controller: 'home' %>
<%= link_to 'New item', new_item_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @items.each do |item| %>
    <tr>
      <td><%= item.title %></td>
      <td><%= item.text %></td>
      <td><%= link_to 'Show', item_path(item) %></td>
      <td><%= link_to 'Edit', edit_item_path(item) %></td>
      <td><%= link_to 'Destroy', item_path(item),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form'  %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @item.text %>
</p>

<h2>Comments</h2>
<%= render @item.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_item_path(@item) %>
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>